use_frameworks!

target 'QYVersionUpdating_Example' do
  pod 'QYVersionUpdating', :path => '../'

  target 'QYVersionUpdating_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
